export const StatesInNG =
    ["Abia",
        "Adamawa",
        "AkwaIbom",
        "Anambra",
        "Bauchi",
        "Bayelsa",
        "Benue",
        "Borno",
        "Cross River",
        "Delta",
        "Ebonyi",
        "Edo",
        "Ekiti",
        "Rivers",
        "Enugu",
        "FCT",
        "Gombe",
        "Imo",
        "Jigawa",
        "Kaduna",
        "Kano",
        "Katsina",
        "Kebbi",
        "Kogi",
        "Kwara",
        "Lagos",
        "Nasarawa",
        "Niger",
        "Ogun",
        "Ondo", "Osun",
        "Oyo",
        "Plateau",
        "Sokoto",
        "Taraba",
        "Yobe",
        "Zamfara"
    ]